# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sanjeev_pb2 as sanjeev__pb2


class SanjeevStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetResponse = channel.unary_unary(
        '/sanjeev.Sanjeev/GetResponse',
        request_serializer=sanjeev__pb2.Prompt.SerializeToString,
        response_deserializer=sanjeev__pb2.Response.FromString,
        )


class SanjeevServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetResponse(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SanjeevServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetResponse': grpc.unary_unary_rpc_method_handler(
          servicer.GetResponse,
          request_deserializer=sanjeev__pb2.Prompt.FromString,
          response_serializer=sanjeev__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sanjeev.Sanjeev', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
