# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sanjeev.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sanjeev.proto',
  package='sanjeev',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rsanjeev.proto\x12\x07sanjeev\"\x16\n\x06Prompt\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t\"\x18\n\x08Response\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t2>\n\x07Sanjeev\x12\x33\n\x0bGetResponse\x12\x0f.sanjeev.Prompt\x1a\x11.sanjeev.Response\"\x00\x62\x06proto3'
)




_PROMPT = _descriptor.Descriptor(
  name='Prompt',
  full_name='sanjeev.Prompt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='sanjeev.Prompt.body', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=48,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='sanjeev.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='sanjeev.Response.body', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['Prompt'] = _PROMPT
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Prompt = _reflection.GeneratedProtocolMessageType('Prompt', (_message.Message,), {
  'DESCRIPTOR' : _PROMPT,
  '__module__' : 'sanjeev_pb2'
  # @@protoc_insertion_point(class_scope:sanjeev.Prompt)
  })
_sym_db.RegisterMessage(Prompt)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'sanjeev_pb2'
  # @@protoc_insertion_point(class_scope:sanjeev.Response)
  })
_sym_db.RegisterMessage(Response)



_SANJEEV = _descriptor.ServiceDescriptor(
  name='Sanjeev',
  full_name='sanjeev.Sanjeev',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=76,
  serialized_end=138,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetResponse',
    full_name='sanjeev.Sanjeev.GetResponse',
    index=0,
    containing_service=None,
    input_type=_PROMPT,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SANJEEV)

DESCRIPTOR.services_by_name['Sanjeev'] = _SANJEEV

# @@protoc_insertion_point(module_scope)
